# Aliases modernes
alias cat="bat --style=auto"
alias ocat="/usr/bin/cat"
alias ols="/usr/bin/ls --color"
alias oll="/usr/bin/ls -lart --color"
alias ll="exa -lar"
alias find="fd"
alias du="dust"
alias top="btop"
alias diff="diff --color=auto"
