exec-once = regreet; hyprctl dispatch exit

# Monitors at native refresh rates
monitor = desc:CORSAIR MEMORY Inc. 34WQHD240-C,3440x1440@240.0,0x1080,1.0
monitor = desc:Iiyama North America PL2770H,1920x1080@165.0,773x0,1.0
monitor = ,preferred,auto,1

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

input {
    kb_layout = us
    kb_variant = intl
}

animations {
    enabled = false
}
