# Dragon Fire color theme for Kitty

# Background & Foreground
background #181616
foreground #e0dcd4
selection_background #fd5622
selection_foreground #181616
url_color #fd5622
cursor #ff7a3d
cursor_text_color #181616

# Normal colors
color0  #0d0c0c
color1  #e53935
color2  #87a987
color3  #ffab40
color4  #8ba4b0
color5  #a292a3
color6  #8ea4a2
color7  #e0dcd4

# Bright colors
color8  #625e5a
color9  #fd5622
color10 #8a9a7b
color11 #ff7a3d
color12 #949fb5
color13 #8992a7
color14 #8ea4a2
color15 #e0dcd4

# Tab bar
active_tab_background   #fd5622
active_tab_foreground   #181616
inactive_tab_background #282727
inactive_tab_foreground #625e5a
