# Kitty Configuration

font_family      JetBrainsMono Nerd Font
font_size        15.0

# Window
window_padding_width 8
background_opacity 0.85
background_blur 20

# Theme
include kanagawa-dragon.conf
